// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/src/main/proto/v1/proto.proto

// Protobuf Java Version: 3.25.1
package proto.v1;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_v1_SayHelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_v1_SayHelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_v1_SayHelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_v1_SayHelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!app/src/main/proto/v1/proto.proto\022\010pro" +
      "to.v1\"\037\n\017SayHelloRequest\022\014\n\004name\030\001 \001(\t\"#" +
      "\n\020SayHelloResponse\022\017\n\007message\030\001 \001(\t2U\n\016G" +
      "reeterService\022C\n\010SayHello\022\031.proto.v1.Say" +
      "HelloRequest\032\032.proto.v1.SayHelloResponse" +
      "\"\000B\014\n\010proto.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_v1_SayHelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_v1_SayHelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_v1_SayHelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_proto_v1_SayHelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_v1_SayHelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_v1_SayHelloResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
