// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/src/main/proto/v1/proto.proto

// Protobuf Java Version: 3.25.1
package proto.v1;

public interface SayHelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.v1.SayHelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
