// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/src/main/proto/v1/proto.proto

// Protobuf Java Version: 3.25.1
package proto.v1;

public interface SayHelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.v1.SayHelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
